name: first flow
on: [push]
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: install dep
              run: npm ci
            - name: run a one-line script
              run: echo Hello, world!
            - name: run lint
              run: npm run lint

    secondjob:
        needs: [firstjob]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: install dep
              run: npm ci
            - name: testing
              run: npm run test
    
    thirdjob:
        needs: [firstjob, secondjob]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: install dep
              run: npm ci
            - name: deploy
              run: npm run build